# Generated by Django 3.2.3 on 2021-05-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BurgerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название продукта')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание продукта')),
                ('grammar', models.IntegerField(default='0', verbose_name='Граммовки')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото продукта')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Бургеры',
            },
        ),
    ]
