# Generated by Django 3.2.3 on 2021-05-19 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_product', '0002_alter_burgerproduct_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='burgerproduct',
            options={'verbose_name': 'Бургеры'},
        ),
    ]
