# Generated by Django 3.2.3 on 2021-05-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.AddField(
            model_name='order',
            name='cart_products',
            field=models.ManyToManyField(to='cart.CartProduct'),
        ),
    ]
