# Generated by Django 3.2.3 on 2021-05-29 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20210527_2016'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
